### ISSUE TITLE
missing icon

### ISSUE THREAD

**Issue by hoyho** [Manouchehri/bash-WSL-context-menu#5]
it miss the orange ubuntu icon of context when running on windows 10 

![image](https://user-images.githubusercontent.com/8370967/34806066-14f0d920-f6bc-11e7-8a23-180ca6115b8a.png)

and device info:
![image](https://user-images.githubusercontent.com/8370967/34806115-52c66dfa-f6bc-11e7-8fea-a28535952d79.png)

**Comment by pestotoast** [comment]
Had the same problem when I installed Ubuntu via the store. This worked for me:
```
[HKEY_CLASSES_ROOT\Directory\Background\shell\WSL]
@="Bash here"
"Icon"="C:\\Program Files\\WindowsApps\\CanonicalGroupLimited.UbuntuonWindows_1604.2017.922.0_x64__79rhkp1fndgsc\\images\\icon.ico"

[HKEY_CLASSES_ROOT\Directory\Background\shell\WSL\command]
@="\"C:\\Windows\\System32\\bash.exe\""
```
If it doesn't work for you, launch the bash and then use ProcessExplorer to find the directory of bash.exe. There you will find the icon and then you can update the icon path.

**Comment by Manouchehri** [comment]
Thanks! If you have time, could you make a pull request with that fix?

**Comment by pestotoast** [comment]
See #7

**Comment by Manouchehri** [comment]
Thanks!

**Comment by Manouchehri** [comment]
Please let me know if there's any issues with the new reg files.
